### PR TITLE
feat(20786): update the openAPI stubs

### PR DESCRIPTION
**Pull request by vanch3d**
See https://hivemq.kanbanize.com/ctrl_board/57/cards/20786/details/

The PR updates the stubs and schemas to the OepnAPI  specs `2024.2`. It adds the missing hooks and mockd payload

### CODE REVIEW

**Review by oli-hivemq — APPROVED** [review]
LGTM 🦣

**Comment by vanch3d** [comment]
There is a bug with the OpenAPI version 2024.3, regarding `DataPolicyValidator` (type is `SCHEMA`, should be `schema` according to docs and cookbook)

```
    DataPolicyValidator:
      type: object
      description: A policy validator which executes the defined validation.
      properties:
        arguments:
          type: object
          description: The required arguments of the referenced validator type.
        type:
          type: string
          description: The type of the validator.
          enum:
          - SCHEMA
      required:
      - arguments
      - type
```

**Comment by vanch3d** [comment]
Problem with the spelling/casing of the SCHEMA enum for the validator. On hold

**Comment by vanch3d** [comment]
This PR is deprecated, due to the upgrading of React Query (#405 ) and significant refactoring. Redo the generation once #405 has been merged and cherry-pick the required bits

**Pull request closed without merging**
